pR1PhiLowerConstraints=pRMIN-pR1Phi;
pR1PhiHigherConstraints=pR1Phi-pRMAX;
pR3PhiLowerConstraints=pRMIN-pR3Phi;
pR3PhiHigherConstraints=pR3Phi-pRMAX;
pRsR1PhiConstraints=pR1Phi-DGPFMAX.*sR1Phi;
pRsR3PhiConstraints=pR3Phi-DGPFMAX.*sR3Phi;
pgqg1PhiLowerConstraints=- pg1Phi(:).*PFConstCap-qg1Phi(:);
pgqg1PhiHigherConstraints=qg1Phi(:)-pg1Phi(:).*PFConstInd;
pgqg1PhiConeConstraints=norms([pg1Phi(:),qg1Phi(:)],2,2)-vec(repmat(sR1Phi,Ml,Mg));
pgpRFc1PhiConstraints=pg1Phi(:)-vec(repmat(pR1Phi,Ml,Mg)).*...
    vec(repmat(ScenarioParams.FgammaLevelsMat(L1PhiSetVec,:),Ml,1))-c1Phi(:);
pgqg3PhiLowerConstraints=   - pg3Phi(:).*PFConstCap -qg3Phi(:);
pgqg3PhiHigherConstraints=qg3Phi(:)-pg3Phi(:).*PFConstInd;
pgqg3PhiConeConstraints=norms([pg3Phi(:),qg3Phi(:)],2,2)-vec(repmat(sR3Phi,Ml,Mg));
pgpRFc3PhiConstraints=pg3Phi(:)-vec(repmat(pR3Phi,Ml,Mg)).*...
            vec(repmat(cell2mat( cellfun(@(x) x(1,:),ScenarioParams.FgammaLevels(N3PhiSet),'UniformOutput',false)),Ml,1))-c3Phi(:);
 vMaxConstraints=norms(v,Inf,2)-VMAX;
 vMinConstraints=   abs(v(1:end-3,:)-repmat(reshape(cell2mat(vHat),NPhases-3,Ml),1,Mg))-...
     abs(repmat(reshape(cell2mat(vHat),NPhases-3,Ml),1,Mg))-VMIN;
   vSlackConstraints=  v(end-2:end,:)-repmat(reshape(cell2mat(ScenarioParams.vS),3,Ml),1,Mg);  
   
   PowerFlowConstraints=vec(pg(1:end-3,:)+sqrt(-1)*qg(1:end-3,:)-...
    repmat(ScenarioParams.LoadLevelsMat(1:end-3,:),1,Mg).*Bus.SLoadVec(1:end-3))...
    -kron(speye(Mg),GammaMatBlockMl)*...
    vec(v(1:end-3,:)-repmat(reshape(cell2mat(vHat),NPhases-3,Ml),1,Mg))+...
   kron(speye(Mg),PhiMatBlockMl)*conj(vec(v(1:end-3,:)-repmat(reshape(cell2mat(vHat),NPhases-3,Ml),1,Mg)))+...
    repmat(cell2mat(nuVector),Mg,1);

PowerInConstraints=SIn(:)-vec(pg(end-2:end,:)+sqrt(-1)*qg(end-2:end,:))+...
    kron(speye(Mg),PhiSMatBlockMl)*conj(vec(v(1:end-3,:)-repmat(reshape(cell2mat(vHat),NPhases-3,Ml),1,Mg)))+...
    repmat(cell2mat(ScenarioParams.nuSVector),Mg,1);
        
Constraints=v2struct(...
    pR1PhiLowerConstraints, pR1PhiHigherConstraints, ...
    pR3PhiLowerConstraints, pR3PhiHigherConstraints,...
    pRsR1PhiConstraints,pRsR3PhiConstraints,...
    pgqg1PhiLowerConstraints,pgqg1PhiHigherConstraints,...
    pgqg1PhiConeConstraints,pgpRFc1PhiConstraints,...
    pgqg3PhiLowerConstraints,pgqg3PhiHigherConstraints,...
    pgqg3PhiConeConstraints,pgpRFc3PhiConstraints,...
vMaxConstraints,vMinConstraints,vSlackConstraints,...
PowerFlowConstraints, PowerInConstraints);

